// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_T3Zsoh1qFtCih_KWAYerC5fnDHBeLqM',
    appId: '1:392556895404:web:a2c0af5099ee1d0730d309',
    messagingSenderId: '392556895404',
    projectId: 'as-academy-a7a8f',
    authDomain: 'as-academy-a7a8f.firebaseapp.com',
    storageBucket: 'as-academy-a7a8f.firebasestorage.app',
    measurementId: 'G-2NGJEM1J70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrY5b_BkQKOtyBPLpWkJ_oB5goVwxnjBE',
    appId: '1:392556895404:android:f16b196a8d6a737430d309',
    messagingSenderId: '392556895404',
    projectId: 'as-academy-a7a8f',
    storageBucket: 'as-academy-a7a8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuEmUtgmwYydr34d2K5CwQEhiAENjV_F8',
    appId: '1:392556895404:ios:f696c3241441b1bf30d309',
    messagingSenderId: '392556895404',
    projectId: 'as-academy-a7a8f',
    storageBucket: 'as-academy-a7a8f.firebasestorage.app',
    iosClientId: '392556895404-ll8l9ai44uhodso592r6l368lshokpre.apps.googleusercontent.com',
    iosBundleId: 'com.example.incrementorstest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuEmUtgmwYydr34d2K5CwQEhiAENjV_F8',
    appId: '1:392556895404:ios:f696c3241441b1bf30d309',
    messagingSenderId: '392556895404',
    projectId: 'as-academy-a7a8f',
    storageBucket: 'as-academy-a7a8f.firebasestorage.app',
    iosClientId: '392556895404-ll8l9ai44uhodso592r6l368lshokpre.apps.googleusercontent.com',
    iosBundleId: 'com.example.incrementorstest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTFX0kwfODpU4EaedzBtRXh7vy8S_VolQ',
    appId: '1:392556895404:web:565e8cb31af1915030d309',
    messagingSenderId: '392556895404',
    projectId: 'as-academy-a7a8f',
    authDomain: 'as-academy-a7a8f.firebaseapp.com',
    storageBucket: 'as-academy-a7a8f.firebasestorage.app',
    measurementId: 'G-2PFFPJQPJ2',
  );
}
